### ISSUE TITLE
Loops running in reverse can overshoot their stopping point

### ISSUE THREAD

**Issue by mjholtzem** [dentedpixel/LeanTween#116]
This is best seen through a tween with a ping pong loop with loop count set to one.

For example if a gameobject tweens from (0,0,0) to (0,10,10) and back, it will end up y < 0.

Seems that replacing 
`if (this.passed > this.time)
    this.passed = this.time;`
in LTDescr.updateInternal with
`this.passed = Mathf.Clamp(this.passed, 0, this.time);`

would fix the issue, but I'm not sure if that would have other intended consequences as I'm not super familiar with the library yet.

**Comment by dentedpixel** [comment]
Hi there, super late at catching up on bugs, but this change does look harmless and I believe you saw the behaviour you did. Unfortunately I wasn't able to recreate it, but I put in a unit test in case it happens again I can catch it.

I added in your code change because it shouldn't effect the rest of the library.

Thanks!
Russ
