### ISSUE TITLE
LeanTween.value - The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by kobyle69** [dentedpixel/LeanTween#125]
The call is ambiguous between the following methods or properties: LeanTween.value(UnityEngine.GameObject, System.Action<float,float>, float, float, float) and LeanTween.value(UnityEngine.GameObject, System.Action<float,object>, float, float, float)

```
public void StopSteerSound()
{
    LeanTween.value(SoundSourceSteering.gameObject, fadeOut, SoundSourceSteering.volume, 0, 0.25f).setOnComplete(() => SoundSourceSteering.Stop());
}

private void fadeOut(float i_Value, object i_SoundSource)
{
    SoundSource.volume = i_Value;
}
```

**Comment by mvshagin** [comment]
Have the same issue. What does the option Action<float,object> do?

**Comment by tsixd** [comment]
I have a similar issue, although with the "setOnUpdateParams" - seems like "setOnUpdateParams/setOnComplete" is not working with the value tweening which uses a callback function. 

I found a workaround using this:

`LeanTween.value( gameObject, 1f, 5f, 5f).setOnUpdate( (float val)=>{ 
 Debug.Log("tweened val:"+val);
} );
`

instead of this:



`LeanTween.value(gameObject, updateValueExampleCallback, 180f, 270f, 1f).setEase(LeanTweenType.easeOutElastic);
void updateValueExampleCallback( float val ){
  Debug.Log("tweened value:"+val+" set this to whatever variable you are tweening...");
}`

see:
http://dentedpixel.com/LeanTweenDocumentation/classes/LeanTween.html

**Comment by dentedpixel** [comment]
You could also solve this by programming it like this:

LeanTween.value(gameObject, (System.Action<float,object>)fadeOut, 1f, 0, 0.25f);

I can see how this is sort of annoying but at least there is a workaround with it :)

The System.Action<float,object> signature is used for passing another object to the update method that you might need.
