### ISSUE TITLE
Out of available spaces for tweening

### ISSUE THREAD

**Issue by vicenterusso** [dentedpixel/LeanTween#56]
My code below is working as expected, but it's throwing this error. I tried to raise init() numbers to 500k but errors persist. Any advice?

*LeanTween - You have run out of available spaces for tweening. To avoid this error increase the number of spaces to available for tweening when you initialize the LeanTween class ex: LeanTween.init( 800 );*

```csharp
void Newspaper()
{
	LeanTween.value(Dialogs[3].gameObject, (v) =>
	{
		Dialogs[3].alpha = v;
	}, 0, 1, 0.2f);

	LeanTween.scale(NewspaperObject, new Vector3(1.15f, 1.15f, 1.15f), 0.6f);

	LeanTween.rotateAround(NewspaperObject, Vector3.forward, -360f, 0.3f).setOnComplete(() =>
	{
		LeanTween.rotateAround(NewspaperObject, Vector3.forward, -360f, 0.4f).setOnComplete(() =>
		{
			LeanTween.scale(NewspaperObject, new Vector3(1f, 1f, 1f), 0.1f);
			var btnBack = Dialogs[4].GetComponentInChildren<Button>();
			btnBack.interactable = true;
			LeanTween.value(Dialogs[4].gameObject, (v) =>
			{
				Dialogs[4].alpha = v;
			}, 0, 1, 0.3f).setDelay(1);

		});

	});

}
```

**Comment by dentedpixel** [comment]
Hey Vincent,
I tried out your sequence of steps, just to make sure there wasn't somehow a bug in LeanTween with that combination. I wasn't able to get any out of space errors.

Is this method just being called once? If it was being called 500k times at once itself I could see why it would run out of space :), but i doubt that is the case. You may wan to print out when it is getting called just to make sure it isn't being called some obscene amount. Otherwise I am not too sure... if you can isolate it to some code that you can share, I would be happy to look into it.

Thanks,
Russ

**Comment by vicenterusso** [comment]
Sure, scenario isolated in this repo: https://github.com/vicenterusso/LeanTweenBugTest

Run the scene and click "next" few times until newspaper shows up.

**Comment by dentedpixel** [comment]
Hi Vincent, I think I found the issue. It looks like you are endlessly calling the NewsPaper method so that eventually that animation sequence will run out of space.

I added an incrementer after calling the NewsPaper method in your example, like:

Newspaper();
DialogSequence++;

This fixed the issue.

**Comment by vicenterusso** [comment]
That's embarrassing! Thanks!
