### ISSUE TITLE
Cancelling tween after finished, if another tween started in the meantime, LeanTween.cancel() cancels the new one instead.

### ISSUE THREAD

**Issue by FREEZX** [dentedpixel/LeanTween#60]
Hi,
Long time user of LeanTween here, love the lib and use it in our game.
So far we didn't rely much on cancelling tweens, and even when we did, we just used .cancel(gameObject), so we didn't have any issues.
However, in some new code we had to cancel one-shot tweens, so we started using LTDescr.cancel(), by keeping a reference of the LTDescr when starting the tween. We want to cancel the tween if it's in progress and do nothing if it's finished.
However, if a tween finishes, and another starts in the meantime, when we call .cancel(id) or LTDescr.cancel(), the new tween gets cancelled instead. The reference's values get replaced, because the values in the array are directly getting manipulated and a new LTDescr is not created, so even .toggle is getting set to the new tween's value. The only thing we can do is use onComplete to circument the issue, but that will get tedious if we have to use it everywhere.
Any better solutions to this one?

**Comment by dentedpixel** [comment]
Thanks! I am glad it's mostly worked out for you :)

This is a common issue that comes up, I have tried to rewrite the documentation so that it doesn't mention using cancel in using the LTDescr object, but instead cancel's based on the id of the object, since this is the most predictive way to use cancel, ex:

int id = LeanTween.move( gameObject, new Vector3(0f,1f,2f), 1f).id; 
LeanTween.cancel( id );

Unfortunately you can't use it like:
LTDescr descr = LeanTween.move( gameObject, new Vector3(0f,1f,2f), 1f); 
LeanTween.cancel( descr.id );
Because the descr can get updated with a new LTDescr object, like you may have noticed.

I have been thinking of making a tutorial for advanced users to go over some of these proper usage issues, but otherwise I don't think much can be done on the API side.

I'd love to see what game you are using LeanTween in.

**Comment by FREEZX** [comment]
Thanks.
So in general it's not smart to keep a reference to LTDescr object at all.
BTW, i'm working on a game called Excubitor:
https://www.youtube.com/watch?v=4RuIFgWGgS8

**Comment by dentedpixel** [comment]
Woah that games look amazing!

Yeah in general unless you are certain it's within the timeframe of the
tween, you shouldn't keep a direct reference to the LTDescr around, but
feel free to keep an id around and then you can retrieve that LTDescr later
like:

LTDescr descr = LeanTween.descr( id );
if(descr!=null){
 // Do what you normally would here
}

On Wed, Dec 2, 2015 at 4:07 AM, Kristijan Trajkovski <
notifications@github.com> wrote:

> Thanks.
> So in general it's not smart to keep a reference to LTDescr object at all.
> BTW, i'm working on a game called Excubitor:
> https://www.youtube.com/watch?v=4RuIFgWGgS8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dentedpixel/LeanTween/issues/60#issuecomment-161228207>
> .
>



-- 
Twitter - http://twitter.com/DentedPixel
Facebook - http://www.facebook.com/DentedPixel
Website - http://dentedpixel.com
